-- Table: public.network_survey_trash

-- DROP TABLE public.network_survey_trash;

CREATE TABLE public.network_survey_trash
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    agency_code character varying DEFAULT 'CTS',
    agency_name character varying DEFAULT 'CTrends Software & Services Ltd.',
    project_code character varying DEFAULT 'BDAWIFI',
    project_name character varying DEFAULT 'Army Public WiFi Project',
    username character varying DEFAULT 'CTS200001',
    person_name character varying DEFAULT 'Mamunur Rahman',
    gender character varying DEFAULT 'Male',
    email character varying DEFAULT 'mrahman2k4@gmail.com',
    mobile character varying DEFAULT '8801610006106',
    address character varying,
    loc_type_code character varying DEFAULT '110',
    loc_type_name character varying DEFAULT 'Network Site',
    loc_code character varying,
    loc_name character varying,
    latitude double precision DEFAULT 23.00,
    longitude double precision DEFAULT 90.00,
    altitude double precision DEFAULT 17.0,
    priority integer DEFAULT 1,
    priority_name character varying DEFAULT 'Platinum',
    potential_customers integer DEFAULT 50,
    pole_type character varying DEFAULT 'No Pole',
    comments character varying,
    point_type character varying DEFAULT 'WiFi Router',
    place_type character varying DEFAULT 'Market',
    power_source character varying DEFAULT 'Commercial',
    custodian_code character varying,
    custodian_name character varying,
    custodian_mobile character varying,
    custodian_email character varying,
    custodian_nid character varying,
    custodian_username character varying,
    custodian_monthly_rent double precision DEFAULT 0.0,
    country_id uuid DEFAULT '0b631485-359f-412d-be3e-85a3ddd32ad6'::uuid,
    country_code character varying DEFAULT 'BD',
    country_telcode character varying DEFAULT '880',
    country_name character varying DEFAULT 'Bangladesh',
    geo_level1_id uuid DEFAULT 'cc8c22e3-8fee-448d-b5a5-52b611ce1fdf'::uuid,
    geo_level1_code character varying DEFAULT '55',
    geo_level1_name character varying DEFAULT 'Rangpur',
    geo_level2_id uuid DEFAULT 'c2ca0894-703e-464a-995c-5bd3f82af235'::uuid,
    geo_level2_code character varying DEFAULT '85',
    geo_level2_name character varying DEFAULT 'Rangpur',
    geo_level3_id uuid DEFAULT '53de4dce-51ab-4064-aee2-6237042c57ee'::uuid,
    geo_level3_code character varying DEFAULT '27',
    geo_level3_name character varying DEFAULT 'Gangachara',
    geo_level4_id uuid,
    geo_level4_code character varying DEFAULT 'NA',
    geo_level4_name character varying DEFAULT 'NA',
    geo_level5_id uuid,
    geo_level5_code character varying DEFAULT 'NA',
    geo_level5_name character varying DEFAULT 'NA',
    geo_level6_id uuid,
    geo_level6_code character varying DEFAULT 'NA',
    geo_level6_name character varying DEFAULT 'NA',
    geo_level7_id uuid,
    geo_level7_code character varying DEFAULT 'NA',
    geo_level7_name character varying DEFAULT 'NA',
    geo_level8_id uuid,
    geo_level8_code character varying DEFAULT 'NA',
    geo_level8_name character varying DEFAULT 'NA',
    geo_level9_id uuid,
    geo_level9_code character varying DEFAULT 'NA',
    geo_level9_name character varying DEFAULT 'NA',
    geography_point_binary geography(Point,4326),
    geography_point_json character varying,
    geography_polygon_binary geography(Point,4326),
    geography_polygon_json character varying,
    om_fee double precision DEFAULT 0.0,
    om_fee_type character varying,
    om_person_address character varying,
    om_person_email character varying,
    om_person_gender character varying,
    om_person_mobile character varying,
    om_person_name character varying,
    om_person_nid character varying,
    om_person_username character varying,
    status character varying DEFAULT 'Draft',
    sync_status character varying DEFAULT 'New',
    survey_date date,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    verfication_date date,
    payment_date date,
    surveyor_remarks character varying,
    verifier_remarks character varying,
    data_digest character varying,
    area_level_full_code character varying(255),
    area_level integer DEFAULT 4,
    area_type character varying(255),
    custodian_address character varying(255),
    location_full_address character varying(255),
    survey_time timestamp without time zone,
    priority_code character varying,
    pole_type_code character varying,
    point_type_code character varying,
    place_type_code character varying,
    power_source_code character varying,
    latitude2 double precision DEFAULT 23.0,
    longitude2 double precision DEFAULT 90.0,
    updated_by_username character varying,
    updated_by_person_name character varying,
    updated_by_email character varying,
    updated_by_mobile character varying,
    export_status character varying DEFAULT 'NOT_EXPORTED',
    CONSTRAINT pk_network_survey_trash_id PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.network_survey_trash
    OWNER to postgres;